# Generated by Django 5.2.8 on 2025-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='chai_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('ML', 'Milk'), ('GR', 'Grass'), ('CH', 'Chai')], default='ML', max_length=2)),
            ],
        ),
    ]
